cloud:
  aws:
    credentials:
      profileName: default
      accessKey:
      secretKey:
      instanceProfile: false
    region:
      auto: false
      static: ap-northeast-1
    stack:
      auto: false